module.exports = {
    "casa": ["hogar", "vivienda", "residencia"],
    "perro": ["canino", "mascota", "perrito"],
    "hola":["holi","hi","holo","como estas","hello"],
    "hi":["holi","hi","holo","como estas","hello"],
    "holo":["holi","hi","holo","como estas","hello"],
    "hello":["holi","hi","holo","como estas","hello"],
    "domicilio":["lugar","locacion","ubicacion","ubi","establecimiento"],
    "lugar":["lugar","locacion","ubicacion","ubi"],
    "ubicacion":["lugar","locacion","ubicacion","ubi","posicion","sitio","puesto"],
    "puesto":["lugar","locacion","ubicacion","ubi","posicion","sitio","puesto"],
    "telefono":["telefono","celular","numero"],
    "celular":["telefono","celular","numero"],
    "numero":["telefono","celular","numero"],
    "movil":["telefono","celular","numero","movil"],
    "gracias":["agradecido","agradezco","muchas gracias",""],
    "adios": ["chao", "hasta luego", "nos vemos", "bye", "nos vidrios"],
    "ayuda": ["asistencia", "auxilio", "socorro", "sálvame"],
    "inicio": ["comenzar", "empezar", "arrancar", "pilas"],
    "opciones": ["alternativas", "posibilidades", "elecciones", "variantes"],
    "información": ["datos", "detalles", "info", "datos de vuelo"],
    "usuario": ["cliente", "visitante", "persona", "user"],
    "respuesta": ["contestación", "reacción", "replies", "lo que sea"],
    "pregunta": ["consulta", "interrogación", "cuestión", "pichón"],
    "entender": ["comprender", "captar", "asimilar", "cachar"],
    "responder": ["contestar", "reaccionar", "replies", "hacer paro"],
    "buscar": ["indagar", "investigar", "rastrear", "chusmear"],
    "cancelar": ["anular", "deshacer", "abortar", "mandar al carajo"],
    "confirmar": ["verificar", "validar", "corroborar", "dar el ok"],
    "enviar": ["mandar", "transmitir", "remesar", "tirar"],
    "comprar": ["adquirir", "obtener", "conseguir", "echar el guante"],
    "vender": ["ofrecer", "negociar", "transar", "dar vueltas"],
    "ayudar": ["colaborar", "apoyar", "auxiliar", "echar la mano"],
    "navegar": ["explorar", "recorrer", "desplazarse", "chamuyar"],
    "ver": ["observar", "mirar", "contemplar", "echar ojo"],
    "agregar": ["añadir", "incluir", "sumar", "meterle"],
    "eliminar": ["quitar", "suprimir", "borrar", "voltear"],
    "editar": ["modificar", "cambiar", "ajustar", "meter mano"],
    "buscar": ["explorar", "indagar", "investigar", "chamuyar"],
    "encontrar": ["hallar", "descubrir", "ubicar", "dar con"],
    "saludar": ["dar la bienvenida", "decir hola", "pronunciar saludos", "mandar un saludito"],
    "tiempo": ["clima", "meteorología", "condiciones atmosféricas", "qué onda con el tiempo"],
    "noticias": ["novedades", "información actual", "últimas noticias", "qué cuentan las noticias"],
    "entretenimiento": ["diversión", "recreación", "ocio", "qué hay para el entretenimiento"],
    "música": ["canciones", "melodías", "temas musicales", "qué suena en la música"],
    "película": ["cine", "film", "largometraje", "qué hay en el cine"],
    "juego": ["diversión", "entretenimiento", "pasatiempo", "qué hay para jugar"],
    "horario": ["agenda", "cronograma", "programación", "a qué hora se hace"],
    "fecha": ["día", "día del mes", "día del año", "en qué fecha estamos"],
    "hora": ["momento", "tiempo", "instante", "a qué hora es"],
    "ubicación": ["lugar", "sitio", "localización", "dónde se encuentra"],
    "dirección": ["ubicación", "posición", "sitio", "cómo llegar"],
    "contacto": ["comunicación", "información de contacto", "datos de contacto", "cómo me contactas"],
    "evento": ["ocasión", "celebración", "acto", "qué evento hay"],
    "amigo": ["compa", "pana", "cuate", "bro", "buddy"],
    "comida": ["alimento", "piqueo", "vianda", "algo pa' picar"],
    "bebida": ["trago", "liquido", "güisqui", "birra"],
    "dinero": ["lana", "plata", "morlacos", "billetes", "feria"],
    "fiesta": ["rumba", "juerga", "parranda", "bote"],
    "casa": ["hogar", "vivienda", "residencia", "chante", "chulapa"],
    "trabajo": ["laburo", "curro", "empleo", "jato"],
    "auto": ["carro", "coche", "vehículo", "máquina"],
    "viaje": ["paseo", "excursión", "tour", "rol"],
};
