FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG REACT_APP_API_URL
ARG REACT_APP_GOOGLE_API_KEY
ARG REACT_APP_CONTRACT_ADDRESS
ARG REACT_APP_DESTINATION_WALLET_ADDRESS
ARG REACT_APP_USDT_CONTRACT_ADDRESS
ARG REACT_APP_CONTRACT_CHAIN_ID
ARG REACT_APP_GOOGLE_MAPS_ID

ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_GOOGLE_API_KEY=$REACT_APP_GOOGLE_API_KEY
ENV REACT_APP_CONTRACT_ADDRESS=$REACT_APP_CONTRACT_ADDRESS
ENV REACT_APP_DESTINATION_WALLET_ADDRESS=$REACT_APP_DESTINATION_WALLET_ADDRESS
ENV REACT_APP_USDT_CONTRACT_ADDRESS=$REACT_APP_USDT_CONTRACT_ADDRESS
ENV REACT_APP_CONTRACT_CHAIN_ID=$REACT_APP_CONTRACT_CHAIN_ID
ENV REACT_APP_GOOGLE_MAPS_ID=$REACT_APP_GOOGLE_MAPS_ID

RUN npm run build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]